export { TripsModule } from './trips.module.js';
export { TripsService, vehicleFits, largestVehicleClass, RIDE_AUTOCOMPLETE_AFTER_MS, TRIPS_QUEUE, TRIP_JOBS, toTripView } from './trips.service.js';
export type { CreateTripInput, TripOrderInput, DeviceStamp, TripTimerJob } from './trips.service.js';
export { TripsRpc, TRIPS_ROLE_CHECKER } from './trips.rpc.js';
export type { RoleChecker } from './trips.rpc.js';
export { TRIP_TRANSITIONS, canTransition, deriveTripState, TripTransitionError } from './trip.machine.js';
export { GEOFENCE_RADIUS_M, haversineMeters, withinGeofence, offsetNorth } from './geofence.js';
export { UNREACHABLE_ESCALATE_AFTER_MS, UNREACHABLE_FAIL_AFTER_MS } from './unreachable.js';
export type { NewStop, TripsRepository } from './trips.repository.js';
export { InMemoryTripsRepository, TRIPS_REPOSITORY } from './trips.repository.js';
export { InMemoryTripOrderLookup, TRIP_ORDER_LOOKUP } from './trip-order.lookup.js';
export type { TripOrderLookup } from './trip-order.lookup.js';
export { TRIP_EVENTS, RecordingTripEvents, EventsServiceAdapter as TripEventsAdapter } from './events.adapter.js';
export type { TripEventEmitter, TripDomainEvent } from './events.adapter.js';
