// Builds src/art/pictures.ts from the approved pictures in src/art/pictures/<group>/<name>.svg
// (Date & Saffron set, locked by Ali on 2026-10-07; style rules in /mnt/project-files/illustrations/STYLE.md).
// The .svg files stay exactly as approved; the app gets each one without its <metadata> block
// (provenance, never drawn). Run after adding or replacing a picture: `pnpm --filter @driver/ui art`.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'art');
const dir = join(root, 'pictures');

/** What the app draws from one .svg file: the file without its metadata and the namespace that only the metadata uses. */
export function drawable(svg) {
  return svg
    .replace(/<metadata>[\s\S]*?<\/metadata>/g, '')
    .replace(/\s+xmlns:c2pa="[^"]*"/g, '')
    .trim();
}

export function collect() {
  const out = [];
  for (const group of readdirSync(dir).sort()) {
    for (const file of readdirSync(join(dir, group)).filter((f) => f.endsWith('.svg')).sort()) {
      out.push({ group, name: file.slice(0, -4), xml: drawable(readFileSync(join(dir, group, file), 'utf8')) });
    }
  }
  const seen = new Set();
  for (const p of out) {
    if (seen.has(p.name)) throw new Error(`Two pictures are called "${p.name}": names must be unique across groups.`);
    seen.add(p.name);
  }
  return out;
}

export function render(pictures) {
  const lines = pictures.map((p) => `  ${JSON.stringify(p.name)}: { group: ${JSON.stringify(p.group)}, xml: ${JSON.stringify(p.xml)} },`);
  return [
    '// Generated by scripts/build-art.mjs from src/art/pictures/<group>/<name>.svg. Do not edit by hand:',
    '// change the .svg and run `pnpm --filter @driver/ui art`.',
    '/* eslint-disable */',
    'export const PICTURES = {',
    ...lines,
    '} as const;',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const pictures = collect();
  writeFileSync(join(root, 'pictures.ts'), render(pictures));
  console.log(`src/art/pictures.ts: ${pictures.length} pictures`);
}
